name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - 'expiration/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        working-directory: ./expiration
        run: docker build -t lukaflores/expiration .
      - name: Login to Docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: docker push lukaflores/expiration
      - name: Install Doctl
        uses: digitalocean/action-doctl@v2
        with:
          token:  ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Get Kubernetes Context
        run: doctl kubernetes cluster kubeconfig save mytailortech
      - name: Restart Deployment
        run: kubectl rollout restart deployment expiration-depl
