name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup and Run Tests
        working-directory: ./auth
        run: npm install && npm run test:ci
        
