name: tests-orders

on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup and Run Tests
        working-directory: ./orders
        run: npm install && npm run test:ci
        
